// Code generated by protoc-gen-go. DO NOT EDIT.
// source: func.proto

package kenda

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FunctionOperationID is the list of existing function handler.
// Handler Function Name Collections.
type FunctionOperationID int32

const (
	FunctionOperationID_GET_SERVER_STATUS                  FunctionOperationID = 0
	FunctionOperationID_GET_BARCODE_INFO                   FunctionOperationID = 1
	FunctionOperationID_UPDATE_BARCODE                     FunctionOperationID = 2
	FunctionOperationID_GET_UPDATE_BARCODE_STATUS_LIST     FunctionOperationID = 3
	FunctionOperationID_GET_EXTEND_DAYS                    FunctionOperationID = 4
	FunctionOperationID_GET_CONTROL_AREA_LIST              FunctionOperationID = 5
	FunctionOperationID_GET_HOLD_REASON_LIST               FunctionOperationID = 6
	FunctionOperationID_GET_PRODUCT_TYPE_LIST              FunctionOperationID = 7
	FunctionOperationID_GET_PRODUCT_GROUP_LIST             FunctionOperationID = 8
	FunctionOperationID_GET_PRODUCT_LIST                   FunctionOperationID = 9
	FunctionOperationID_GET_RECIPE_LIST                    FunctionOperationID = 10
	FunctionOperationID_GET_PLAN_LIST                      FunctionOperationID = 11
	FunctionOperationID_ADD_PLAN                           FunctionOperationID = 12
	FunctionOperationID_CREATE_STATION_SCHEDULING          FunctionOperationID = 13
	FunctionOperationID_GET_STATION_SCHEDULING             FunctionOperationID = 14
	FunctionOperationID_UPDATE_STATION_SCHEDULING          FunctionOperationID = 15
	FunctionOperationID_GET_STATION_LIST                   FunctionOperationID = 16
	FunctionOperationID_ADD_MATERIAL                       FunctionOperationID = 17
	FunctionOperationID_GET_WAREHOUSE_INFO                 FunctionOperationID = 18
	FunctionOperationID_WAREHOUSE_TRANSACTION              FunctionOperationID = 19
	FunctionOperationID_GET_RECIPE_IDS                     FunctionOperationID = 20
	FunctionOperationID_GET_RECIPE_PROCESS_LIST            FunctionOperationID = 21
	FunctionOperationID_GET_MATERIAL_RESOURCE_INFO         FunctionOperationID = 25
	FunctionOperationID_GET_SITE_MATERIAL_LIST             FunctionOperationID = 26
	FunctionOperationID_BIND_RESOURCE                      FunctionOperationID = 27
	FunctionOperationID_CHANGE_USER_PASSWORD               FunctionOperationID = 28
	FunctionOperationID_LIST_CARRIER                       FunctionOperationID = 29
	FunctionOperationID_CREATE_CARRIER                     FunctionOperationID = 30
	FunctionOperationID_UPDATE_CARRIER                     FunctionOperationID = 31
	FunctionOperationID_DELETE_CARRIER                     FunctionOperationID = 32
	FunctionOperationID_GET_ROLE_LIST                      FunctionOperationID = 33
	FunctionOperationID_LIST_AUTHORIZED_ACCOUNT            FunctionOperationID = 34
	FunctionOperationID_LIST_UNAUTHORIZED_ACCOUNT          FunctionOperationID = 35
	FunctionOperationID_CREATE_ACCOUNT                     FunctionOperationID = 36
	FunctionOperationID_UPDATE_ACCOUNT                     FunctionOperationID = 37
	FunctionOperationID_DELETE_ACCOUNT                     FunctionOperationID = 38
	FunctionOperationID_SITE_TYPE_LIST                     FunctionOperationID = 39
	FunctionOperationID_SITE_SUBTYPE_LIST                  FunctionOperationID = 40
	FunctionOperationID_LIST_STATION_INFO                  FunctionOperationID = 41
	FunctionOperationID_CREATE_STATION                     FunctionOperationID = 42
	FunctionOperationID_UPDATE_STATION_INFO                FunctionOperationID = 43
	FunctionOperationID_DELETE_STATION                     FunctionOperationID = 44
	FunctionOperationID_LIST_STATION_STATE                 FunctionOperationID = 45
	FunctionOperationID_GET_MATERIAL_RESOURCE_INFO_BY_TYPE FunctionOperationID = 46
	FunctionOperationID_LIST_MATERIAL_STATUS               FunctionOperationID = 47
	FunctionOperationID_SPLIT_MATERIAL                     FunctionOperationID = 48
	FunctionOperationID_DOWNLOAD_MATERIAL_RESOURCE         FunctionOperationID = 49
	FunctionOperationID_CHANGE_WORK_ORDER_STATUS           FunctionOperationID = 50
	FunctionOperationID_LIST_WORK_ORDERS                   FunctionOperationID = 51
	FunctionOperationID_GET_WORK_ORDER_INFORMATION         FunctionOperationID = 52
	FunctionOperationID_GET_SITE_INFORMATION               FunctionOperationID = 53
	FunctionOperationID_GET_TOOL_ID                        FunctionOperationID = 54
	FunctionOperationID_FEED_COLLECT                       FunctionOperationID = 55
	FunctionOperationID_LIST_STATIONS                      FunctionOperationID = 56
	FunctionOperationID_SET_STATION_CONFIG                 FunctionOperationID = 57
	FunctionOperationID_GET_STATION_CONFIG                 FunctionOperationID = 58
	FunctionOperationID_LIST_STATION_SITES                 FunctionOperationID = 59
	FunctionOperationID_PRINT_MATERIAL_RESOURCE            FunctionOperationID = 60
	FunctionOperationID_LIST_DEPARTMENT_IDS                FunctionOperationID = 61
	FunctionOperationID_STATION_FORCE_SIGN_IN              FunctionOperationID = 62
	FunctionOperationID_STATION_SIGN_OUT                   FunctionOperationID = 63
	FunctionOperationID_GET_STATION_OPERATOR               FunctionOperationID = 64
	FunctionOperationID_UPDATE_WORK_ORDER                  FunctionOperationID = 65
	FunctionOperationID_CREATE_WORK_ORDERS_FROM_FILE       FunctionOperationID = 66
	FunctionOperationID_DOWNLOAD_PRE_MATERIAL_RESOURCE     FunctionOperationID = 67
	FunctionOperationID_MES_FEED                           FunctionOperationID = 69
	FunctionOperationID_MES_COLLECT                        FunctionOperationID = 70
	FunctionOperationID_LIST_WORK_ORDERS_RATE              FunctionOperationID = 71
)

var FunctionOperationID_name = map[int32]string{
	0:  "GET_SERVER_STATUS",
	1:  "GET_BARCODE_INFO",
	2:  "UPDATE_BARCODE",
	3:  "GET_UPDATE_BARCODE_STATUS_LIST",
	4:  "GET_EXTEND_DAYS",
	5:  "GET_CONTROL_AREA_LIST",
	6:  "GET_HOLD_REASON_LIST",
	7:  "GET_PRODUCT_TYPE_LIST",
	8:  "GET_PRODUCT_GROUP_LIST",
	9:  "GET_PRODUCT_LIST",
	10: "GET_RECIPE_LIST",
	11: "GET_PLAN_LIST",
	12: "ADD_PLAN",
	13: "CREATE_STATION_SCHEDULING",
	14: "GET_STATION_SCHEDULING",
	15: "UPDATE_STATION_SCHEDULING",
	16: "GET_STATION_LIST",
	17: "ADD_MATERIAL",
	18: "GET_WAREHOUSE_INFO",
	19: "WAREHOUSE_TRANSACTION",
	20: "GET_RECIPE_IDS",
	21: "GET_RECIPE_PROCESS_LIST",
	25: "GET_MATERIAL_RESOURCE_INFO",
	26: "GET_SITE_MATERIAL_LIST",
	27: "BIND_RESOURCE",
	28: "CHANGE_USER_PASSWORD",
	29: "LIST_CARRIER",
	30: "CREATE_CARRIER",
	31: "UPDATE_CARRIER",
	32: "DELETE_CARRIER",
	33: "GET_ROLE_LIST",
	34: "LIST_AUTHORIZED_ACCOUNT",
	35: "LIST_UNAUTHORIZED_ACCOUNT",
	36: "CREATE_ACCOUNT",
	37: "UPDATE_ACCOUNT",
	38: "DELETE_ACCOUNT",
	39: "SITE_TYPE_LIST",
	40: "SITE_SUBTYPE_LIST",
	41: "LIST_STATION_INFO",
	42: "CREATE_STATION",
	43: "UPDATE_STATION_INFO",
	44: "DELETE_STATION",
	45: "LIST_STATION_STATE",
	46: "GET_MATERIAL_RESOURCE_INFO_BY_TYPE",
	47: "LIST_MATERIAL_STATUS",
	48: "SPLIT_MATERIAL",
	49: "DOWNLOAD_MATERIAL_RESOURCE",
	50: "CHANGE_WORK_ORDER_STATUS",
	51: "LIST_WORK_ORDERS",
	52: "GET_WORK_ORDER_INFORMATION",
	53: "GET_SITE_INFORMATION",
	54: "GET_TOOL_ID",
	55: "FEED_COLLECT",
	56: "LIST_STATIONS",
	57: "SET_STATION_CONFIG",
	58: "GET_STATION_CONFIG",
	59: "LIST_STATION_SITES",
	60: "PRINT_MATERIAL_RESOURCE",
	61: "LIST_DEPARTMENT_IDS",
	62: "STATION_FORCE_SIGN_IN",
	63: "STATION_SIGN_OUT",
	64: "GET_STATION_OPERATOR",
	65: "UPDATE_WORK_ORDER",
	66: "CREATE_WORK_ORDERS_FROM_FILE",
	67: "DOWNLOAD_PRE_MATERIAL_RESOURCE",
	69: "MES_FEED",
	70: "MES_COLLECT",
	71: "LIST_WORK_ORDERS_RATE",
}

var FunctionOperationID_value = map[string]int32{
	"GET_SERVER_STATUS":                  0,
	"GET_BARCODE_INFO":                   1,
	"UPDATE_BARCODE":                     2,
	"GET_UPDATE_BARCODE_STATUS_LIST":     3,
	"GET_EXTEND_DAYS":                    4,
	"GET_CONTROL_AREA_LIST":              5,
	"GET_HOLD_REASON_LIST":               6,
	"GET_PRODUCT_TYPE_LIST":              7,
	"GET_PRODUCT_GROUP_LIST":             8,
	"GET_PRODUCT_LIST":                   9,
	"GET_RECIPE_LIST":                    10,
	"GET_PLAN_LIST":                      11,
	"ADD_PLAN":                           12,
	"CREATE_STATION_SCHEDULING":          13,
	"GET_STATION_SCHEDULING":             14,
	"UPDATE_STATION_SCHEDULING":          15,
	"GET_STATION_LIST":                   16,
	"ADD_MATERIAL":                       17,
	"GET_WAREHOUSE_INFO":                 18,
	"WAREHOUSE_TRANSACTION":              19,
	"GET_RECIPE_IDS":                     20,
	"GET_RECIPE_PROCESS_LIST":            21,
	"GET_MATERIAL_RESOURCE_INFO":         25,
	"GET_SITE_MATERIAL_LIST":             26,
	"BIND_RESOURCE":                      27,
	"CHANGE_USER_PASSWORD":               28,
	"LIST_CARRIER":                       29,
	"CREATE_CARRIER":                     30,
	"UPDATE_CARRIER":                     31,
	"DELETE_CARRIER":                     32,
	"GET_ROLE_LIST":                      33,
	"LIST_AUTHORIZED_ACCOUNT":            34,
	"LIST_UNAUTHORIZED_ACCOUNT":          35,
	"CREATE_ACCOUNT":                     36,
	"UPDATE_ACCOUNT":                     37,
	"DELETE_ACCOUNT":                     38,
	"SITE_TYPE_LIST":                     39,
	"SITE_SUBTYPE_LIST":                  40,
	"LIST_STATION_INFO":                  41,
	"CREATE_STATION":                     42,
	"UPDATE_STATION_INFO":                43,
	"DELETE_STATION":                     44,
	"LIST_STATION_STATE":                 45,
	"GET_MATERIAL_RESOURCE_INFO_BY_TYPE": 46,
	"LIST_MATERIAL_STATUS":               47,
	"SPLIT_MATERIAL":                     48,
	"DOWNLOAD_MATERIAL_RESOURCE":         49,
	"CHANGE_WORK_ORDER_STATUS":           50,
	"LIST_WORK_ORDERS":                   51,
	"GET_WORK_ORDER_INFORMATION":         52,
	"GET_SITE_INFORMATION":               53,
	"GET_TOOL_ID":                        54,
	"FEED_COLLECT":                       55,
	"LIST_STATIONS":                      56,
	"SET_STATION_CONFIG":                 57,
	"GET_STATION_CONFIG":                 58,
	"LIST_STATION_SITES":                 59,
	"PRINT_MATERIAL_RESOURCE":            60,
	"LIST_DEPARTMENT_IDS":                61,
	"STATION_FORCE_SIGN_IN":              62,
	"STATION_SIGN_OUT":                   63,
	"GET_STATION_OPERATOR":               64,
	"UPDATE_WORK_ORDER":                  65,
	"CREATE_WORK_ORDERS_FROM_FILE":       66,
	"DOWNLOAD_PRE_MATERIAL_RESOURCE":     67,
	"MES_FEED":                           69,
	"MES_COLLECT":                        70,
	"LIST_WORK_ORDERS_RATE":              71,
}

func (x FunctionOperationID) String() string {
	return proto.EnumName(FunctionOperationID_name, int32(x))
}

func (FunctionOperationID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b1bdb44c2d3501c, []int{0}
}

func init() {
	proto.RegisterEnum("kenda.FunctionOperationID", FunctionOperationID_name, FunctionOperationID_value)
}

func init() { proto.RegisterFile("func.proto", fileDescriptor_6b1bdb44c2d3501c) }

var fileDescriptor_6b1bdb44c2d3501c = []byte{
	// 784 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0xfb, 0x73, 0x1b, 0x35,
	0x10, 0xe6, 0xd5, 0x52, 0xd4, 0xa4, 0xd9, 0xc8, 0x49, 0xdb, 0xa4, 0x69, 0x28, 0x01, 0x0a, 0x14,
	0x28, 0x8f, 0xf2, 0x7e, 0xcb, 0xd2, 0xde, 0x59, 0xc3, 0x59, 0xba, 0x59, 0xe9, 0x30, 0xe1, 0x17,
	0x4d, 0x29, 0x65, 0x86, 0x61, 0xc6, 0xe9, 0x74, 0xda, 0xff, 0x80, 0x3f, 0x9c, 0x59, 0xf9, 0xe4,
	0xbb, 0xa6, 0xee, 0x4f, 0xb6, 0xbf, 0x6f, 0x57, 0xbb, 0xfb, 0xed, 0x27, 0x59, 0x88, 0xbf, 0x9f,
	0x2e, 0x1f, 0xdc, 0x7d, 0xf4, 0xf8, 0xec, 0xc9, 0x99, 0xbc, 0xf0, 0xef, 0xc3, 0xe5, 0x5f, 0xf7,
	0xef, 0xfc, 0xb7, 0x2d, 0x26, 0xd5, 0xd3, 0xe5, 0x83, 0x27, 0xff, 0x9c, 0x2d, 0xfd, 0xa3, 0x87,
	0x8f, 0xef, 0xf3, 0x17, 0x6b, 0xe4, 0xbe, 0xd8, 0xad, 0x31, 0xa6, 0x80, 0xf4, 0x1b, 0x52, 0x0a,
	0x51, 0xc5, 0x2e, 0xc0, 0x4b, 0x72, 0x4f, 0x00, 0xc3, 0x53, 0x45, 0xda, 0x1b, 0x4c, 0xd6, 0x55,
	0x1e, 0x5e, 0x96, 0x52, 0x5c, 0xe9, 0x5a, 0xa3, 0x22, 0x16, 0x02, 0x5e, 0x91, 0x27, 0xe2, 0x98,
	0x23, 0x9f, 0xc5, 0xfb, 0x83, 0x52, 0x63, 0x43, 0x84, 0x57, 0xe5, 0x44, 0xec, 0x70, 0x0c, 0xfe,
	0x1e, 0xd1, 0x99, 0x64, 0xd4, 0x69, 0x80, 0xd7, 0xe4, 0x81, 0xd8, 0x67, 0x50, 0x7b, 0x17, 0xc9,
	0x37, 0x49, 0x11, 0xaa, 0x55, 0xfc, 0x05, 0x79, 0x5d, 0xec, 0x31, 0x35, 0xf3, 0x8d, 0x49, 0x84,
	0x2a, 0x78, 0xb7, 0x62, 0x2e, 0x96, 0xa4, 0x96, 0xbc, 0xe9, 0x74, 0x4c, 0xf1, 0xb4, 0xc5, 0x15,
	0xf5, 0xba, 0x3c, 0x14, 0x57, 0xc7, 0x54, 0x4d, 0xbe, 0x6b, 0x57, 0xdc, 0xa5, 0x32, 0x4e, 0xe1,
	0x32, 0xfa, 0x46, 0x69, 0x8b, 0x50, 0xdb, 0x72, 0x8c, 0x90, 0xbb, 0x62, 0x3b, 0x87, 0x36, 0xaa,
	0x2f, 0x7a, 0x59, 0x6e, 0x89, 0x4b, 0xca, 0x98, 0x0c, 0xc1, 0x96, 0xbc, 0x29, 0x0e, 0x34, 0x21,
	0x0f, 0xcb, 0x43, 0x5a, 0xef, 0x52, 0xd0, 0x33, 0x34, 0x5d, 0x63, 0x5d, 0x0d, 0xdb, 0xa5, 0x8d,
	0x0d, 0xdc, 0x15, 0x4e, 0xed, 0x75, 0xda, 0x40, 0xef, 0x94, 0x2e, 0x0b, 0x97, 0xab, 0x83, 0x04,
	0xb1, 0xc5, 0xd5, 0xe7, 0x2a, 0x22, 0x59, 0xd5, 0xc0, 0xae, 0xbc, 0x2a, 0x24, 0xc7, 0x2d, 0x14,
	0xe1, 0xcc, 0x77, 0xa1, 0x5f, 0x8f, 0x64, 0x71, 0x06, 0x2c, 0x92, 0x72, 0x41, 0x69, 0x3e, 0x09,
	0x26, 0xbc, 0xb9, 0xd1, 0xa8, 0xd6, 0x04, 0xd8, 0x93, 0x37, 0xc4, 0xb5, 0x11, 0xd6, 0x92, 0xd7,
	0x18, 0xfa, 0x95, 0xed, 0xcb, 0x63, 0x71, 0xc8, 0x64, 0xa9, 0x9a, 0x08, 0x83, 0xef, 0x48, 0xf7,
	0xb5, 0x0e, 0xd6, 0x63, 0xda, 0x88, 0x43, 0x50, 0xce, 0x3d, 0x64, 0x09, 0xa7, 0xd6, 0x99, 0x75,
	0x0e, 0xdc, 0xe0, 0x8d, 0xea, 0x99, 0x72, 0x35, 0xa6, 0x2e, 0x20, 0xa5, 0x56, 0x85, 0xb0, 0xf0,
	0x64, 0xe0, 0x88, 0xc7, 0xe3, 0xb4, 0xa4, 0x15, 0x91, 0x45, 0x82, 0x9b, 0xdc, 0x6b, 0x2f, 0x70,
	0xc1, 0x8e, 0x47, 0xce, 0x2b, 0xd8, 0x9b, 0x8c, 0x19, 0x6c, 0x70, 0x84, 0xdd, 0x2a, 0xdb, 0x23,
	0xdf, 0xf4, 0x0b, 0x7d, 0x8b, 0xc7, 0xcc, 0x05, 0x54, 0x17, 0x67, 0x9e, 0xec, 0x1f, 0x68, 0x92,
	0xd2, 0xda, 0x77, 0x2e, 0xc2, 0x09, 0x6f, 0x24, 0x93, 0x9d, 0xdb, 0x40, 0xbf, 0x3d, 0x6a, 0xa5,
	0x60, 0xef, 0x8c, 0x5a, 0x29, 0xd8, 0xbb, 0xa3, 0x56, 0x0a, 0x76, 0x9b, 0xb1, 0xac, 0xce, 0xe0,
	0xd1, 0xf7, 0xf8, 0xb6, 0x65, 0x2c, 0x74, 0xd3, 0x01, 0x7e, 0x9f, 0xe1, 0xdc, 0x45, 0xd9, 0x7c,
	0xd6, 0xf8, 0x83, 0x51, 0xf5, 0x9e, 0x80, 0x3b, 0xf2, 0x9a, 0x98, 0x9c, 0xb3, 0x50, 0x0e, 0xfe,
	0x70, 0xd4, 0x42, 0x09, 0xfe, 0x88, 0x8d, 0xf2, 0xcc, 0xb9, 0xfc, 0x89, 0xf0, 0xb1, 0xbc, 0x2d,
	0x4e, 0x5e, 0xbc, 0xdc, 0x34, 0x3d, 0xcd, 0x3d, 0xc3, 0x5d, 0xde, 0x5a, 0xce, 0x5f, 0x07, 0xf6,
	0xef, 0xc3, 0x27, 0x79, 0xb8, 0xb6, 0xb1, 0x03, 0x05, 0x9f, 0xb2, 0x65, 0x8c, 0x5f, 0xb8, 0xc6,
	0x2b, 0xf3, 0xfc, 0xd1, 0xf0, 0x99, 0x3c, 0x12, 0xd7, 0x7b, 0x0f, 0x2c, 0x3c, 0xfd, 0x9a, 0x3c,
	0x99, 0xe1, 0xc5, 0xf9, 0x9c, 0xcd, 0x9f, 0x6b, 0x0d, 0x5c, 0x80, 0x7b, 0xc5, 0x86, 0xa3, 0x04,
	0x6e, 0x91, 0xe6, 0xab, 0x09, 0xbf, 0x28, 0x2f, 0x45, 0x16, 0x75, 0xcc, 0x7c, 0x29, 0x77, 0xc4,
	0x65, 0x66, 0xa2, 0xf7, 0x4d, 0xb2, 0x06, 0xbe, 0x62, 0xa3, 0x55, 0x88, 0x26, 0x69, 0xdf, 0x34,
	0xa8, 0x23, 0x7c, 0xcd, 0x66, 0x19, 0xcb, 0x13, 0xe0, 0x1b, 0x56, 0x2c, 0x8c, 0xae, 0xa0, 0xf6,
	0xae, 0xb2, 0x35, 0x7c, 0x5b, 0xae, 0xdc, 0x39, 0xfc, 0xbb, 0xe7, 0x15, 0xb6, 0x11, 0x03, 0x7c,
	0xcf, 0xa6, 0x6b, 0xc9, 0xba, 0x0d, 0x1a, 0xc3, 0x0f, 0xbc, 0xc3, 0x9c, 0x64, 0xb0, 0x55, 0x14,
	0xe7, 0xe8, 0x62, 0xbe, 0x91, 0x3f, 0xf2, 0x05, 0x2e, 0x07, 0x55, 0x9e, 0xf7, 0x11, 0x6c, 0xcd,
	0x0b, 0x86, 0x9f, 0x58, 0x9e, 0xa1, 0x46, 0xed, 0x92, 0xef, 0x22, 0xfc, 0xbc, 0x1e, 0xbf, 0x67,
	0x7c, 0x8b, 0xa4, 0xa2, 0x27, 0xf8, 0x85, 0x2d, 0xd5, 0xfb, 0x64, 0xd0, 0x0e, 0x94, 0xbc, 0x25,
	0x8e, 0x7a, 0x4b, 0x8d, 0x74, 0x4e, 0x15, 0xf9, 0x79, 0xaa, 0x6c, 0x83, 0x30, 0xe5, 0xf7, 0x7c,
	0xbd, 0xc5, 0x96, 0x70, 0xc3, 0x00, 0x9a, 0x1f, 0xc4, 0x39, 0x86, 0xc4, 0x72, 0x02, 0xb2, 0xd2,
	0xfc, 0xab, 0xe8, 0x5a, 0xf1, 0x18, 0xe7, 0x57, 0x99, 0x88, 0x9d, 0x57, 0xff, 0x79, 0x31, 0xff,
	0x29, 0xdd, 0xfb, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x9b, 0x97, 0xd9, 0xa2, 0x06, 0x00, 0x00,
}
