<template>
  <div class="app-container">
    <el-header class="header-style">
      {{ $t('router.materialCreate') }}
    </el-header>
    <el-form
      ref="materialCreateDataForm"
      :model="tempMaterialCreateInfo"
      label-position="left"
      label-width="5rem"
      :rules="materialCreateRules"
      autocomplete
    >
      <el-form-item
        :label="$t('system.departmentID')"
      >
        <el-select
          id="departmentID"
          v-model="departmentOIDValue"
          filterable
          :placeholder="$t('system.departmentID')"
          @change="onGetProductTypeList(departmentOIDValue)"
        >
          <el-option
            v-for="item in departmentInfoList"
            :id="item.label.ID"
            :key="item.label.OID"
            :label="item.label.ID"
            :value="item.label.OID"
          />
        </el-select>
      </el-form-item>
      <el-form-item
        :label="$t('system.productType')"
        prop="resource.productType"
      >
        <el-select
          id="productType"
          v-model="tempMaterialCreateInfo.resource.productType"
          filterable
          :placeholder="$t('system.productType')"
          @change="onGetProductList(tempMaterialCreateInfo.resource.productType)"
        >
          <el-option
            v-for="item in productTypeInfoList"
            :id="item.type"
            :key="item.type"
            :label="item.type"
            :value="item.type"
          />
        </el-select>
      </el-form-item>
      <el-form-item
        :label="$t('system.productID')"
        prop="resource.productID"
      >
        <el-select
          id="productID"
          v-model="tempMaterialCreateInfo.resource.productID"
          filterable
          :placeholder="$t('system.productID')"
        >
          <el-option
            v-for="item in productInfoList"
            :id="item"
            :key="item"
            :label="item"
            :value="item"
          />
        </el-select>
      </el-form-item>
      <el-form-item
        :label="$t('system.materialGrade')"
        prop="resource.grade"
      >
        <el-input
          id="grade"
          v-model="tempMaterialCreateInfo.resource.grade"
        />
      </el-form-item>
      <el-form-item
        :label="$t('system.inventory')"
        prop="resource.quantity"
      >
        <el-input-number
          id="quantity"
          v-model="tempMaterialCreateInfo.resource.quantity"
          :min="0"
        />
      </el-form-item>
      <el-form-item
        :label="$t('system.unit')"
        prop="resource.unit"
      >
        <el-input
          id="unit"
          v-model="tempMaterialCreateInfo.resource.unit"
        />
      </el-form-item>
      <el-form-item
        :label="$t('system.lotNumber')"
        prop="resource.lotNumber"
      >
        <el-input
          id="lotNumber"
          v-model="tempMaterialCreateInfo.resource.lotNumber"
        />
      </el-form-item>
      <el-form-item
        :label="$t('system.productionTime')"
        prop="resource.productionTime"
      >
        <el-date-picker
          id="productionTime"
          v-model="tempMaterialCreateInfo.resource.productionTime"
          type="datetime"
        />
      </el-form-item>
      <el-form-item
        :label="$t('system.expirationTime')"
        prop="resource.expiryTime"
      >
        <el-date-picker
          id="expiryTime"
          v-model="tempMaterialCreateInfo.resource.expiryTime"
          type="datetime"
        />
      </el-form-item>
      <el-form-item
        :label="$t('system.warehouse')"
        prop="warehouse.ID"
      >
        <el-input
          id="warehouseID"
          v-model="tempMaterialCreateInfo.warehouse.ID"
          type="text"
          maxlength="1"
          show-word-limit
        />
      </el-form-item>
      <el-form-item
        :label="$t('system.location')"
        prop="warehouse.location"
      >
        <el-input
          id="warehouseLocation"
          v-model="tempMaterialCreateInfo.warehouse.location"
          type="text"
          maxlength="2"
          show-word-limit
        />
      </el-form-item>
    </el-form>
    <el-button
      id="confirm"
      type="primary"
      @click="createMaterialToDB()"
    >
      {{ $t('share.confirm') }}
    </el-button>
  </div>
</template>
<script src="./materialCreate.ts" lang="ts"></script>
<style src="./materialCreate.css"></style>
